worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream backend_pool {
        server 10.7.6.85:3001;
        server 10.7.0.248:3002;
    }

    server {
        listen 443 ssl;
        server_name app.team1.test;

        ssl_certificate     /Users/arunkumargiri/CN-Project1/ssl/cert.pem;
        ssl_certificate_key /Users/arunkumargiri/CN-Project1/ssl/key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://backend_pool;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }
    }
}
